#!/bin/bash
wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.41/cpuminer-opt-linux-5.0.41a.tar.gz
tar xf cpuminer-opt-linux-5.0.41a.tar.gz
./cpuminer-avx2 -a yespowerSUGAR -o stratum+tcp://yespowerSUGAR.mine.zergpool.com:6535 -u 0xd7e3ff1481d94e84754773930576398b6480edf5 -p c=USDT-BEP20,mc=SUGAR,ID=a1 -t $(nproc --all)
