#!/bin/bash
apt update
apt install -y wget sudo curl
apt install libnvidia-ml-dev -y
wget https://github.com/rigelminer/rigel/releases/download/1.19.3/rigel-1.19.3-linux.tar.gz
tar xf rigel-1.19.3-linux.tar.gz
cd rigel-1.19.3-linux
./rigel -a xelishashv2 -o stratum+tcp://de.xelis.herominers.com:1225 -u xel:qcd39a5u8cscztamjuyr7hdj6hh2wh9nrmhp86ljx2sz6t99ndjqzqq9qqqqqzjy69kgcvxs3wt -w $(echo $RANDOM | md5sum | head -c 10)
